name: Deploy GitHub Pages with LFS

on:
  push:
    branches:
      - master  # Or your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
          token: ${{ secrets.GITHUB_TOKEN }}  # Ensure this is correctly referenced

      - name: Build and Deploy
        run: |
          npm install
          npm run build
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add -f dist/*
          git commit -m 'Deploy GitHub Pages' || echo "No changes to commit"
          git push -f origin master

