name: Deploy GitHub Pages with LFS

on:
  push:
    branches:
      - master  # Or your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true 

      - name: Build and Deploy
        run: |
          npm install
          npm run build
          # Then, deploy to GitHub Pages (adjust for your setup)
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add -f dist/*  # Force-add the built files, replace 'dist' with your build directory
          git commit -m 'Deploy GitHub Pages' || echo "No changes to commit"
    	  git remote set-url origin https://${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/aksylumoed/aksylumoed.github.io.git
          git push -f origin master  

